### ISSUE TITLE
Stuck at the buildMREUnityRuntimeDLL.bat build stage

### ISSUE THREAD

**Issue by andybak** [microsoft/mixed-reality-extension-unity#131]
(For multiple reasons which I'd rather not go into right now...)

Rather my question is "why not distribute a compiled DLL?"

Installing an entire C++ build tool-chain is a fairly onerous requirement for something aimed at Unity devs.

**Comment by eanders-MS** [comment]
Sorry this is causing you problems. We plan to start distributing precompiled DLLs at some point. Thanks for taking the time to bring it up here. That helps us understand how to prioritize the work. Associated: https://github.com/microsoft/mixed-reality-extension-sdk/issues/317.

Closing this issue, but if you'd like help getting unstuck, reply here.

**Comment by andybak** [comment]
I'm not sure that ticket is quite what I was requesting. NuGet just isn't part of the Unity ecosystem. If anything release a UPM package or a traditional asset. But most people would be happy with a Github repo that can be added to a project without requiring a complex C++ build step.

**Comment by eanders-MS** [comment]
Agreed. We need to do some research on this before deciding how to package these. Unity Package Manager looks promising. Simply making releases to GitHub is also an appealing option. Certainly better than making people build it.
